export const REWARD_CONFIG = {
    POST_FEE: 20,
    COMMENT_FEE: 10,
    LIKE_FEE: 1,
    
    FEE_SPLIT: {
        PRIZE_POOL: 80,
        PLATFORM_FEE: 15,
        LIKER_RESERVE: 5
    },
    
    TOP_POST_REWARD_PERCENT: 80,
    TOP_COMMENT_REWARD_PERCENT: 80,
    
    LIKER_REWARD_POST: 3,
    LIKER_REWARD_COMMENT: 2,
    
    ACTIVE_START_HOUR: 8,
    FREEZE_START_HOUR: 6,
    EVALUATION_DURATION_HOURS: 2,
    
    MAX_POSTS_PER_DAY: 10,
    MAX_COMMENTS_PER_DAY: 50,
    MAX_LIKES_PER_DAY: 100,
    
    INITIAL_REPUTATION: 50,
    WIN_REPUTATION_BONUS: 5,
    FRAUD_REPUTATION_PENALTY: 10,
    
    INITIAL_BALANCE: 100
};
